### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by avdv**
Hi,

we are using refined and play-json, and thusly play-json-refined. Now we wanted to switch to Scala 2.13 but noticed this library is not yet up-to-date.

So, I have made a few changes and raised a few version numbers here and there.

Hope you can put out a new release soon. :smiley_cat: 

Thanks!

### CODE REVIEW

**Comment by lunaryorn** [comment]
@avdv Much appreciated, but I must admit that I'm not using play-json anymore, so if you have a (commercial) interest in this library I recommend you fork it and publish it yourself w/ a different group ID.

**Comment by avdv** [comment]
> @avdv Much appreciated, but I must admit that I'm not using play-json anymore, so if you have a (commercial) interest in this library I recommend you fork it and publish it yourself w/ a different group ID.

Fair enough - will do, thanks!

**Comment by lunaryorn** [comment]
@avdv That said, I'm also happy to transfer ownership of this repository if you like; I'd only insist that you publish under a different group ID :)

**Comment by avdv** [comment]
> @avdv That said, I'm also happy to transfer ownership of this repository if you like; I'd only insist that you publish under a different group ID :)

@lunaryorn :ok_man: Sure, let's do this!

**Comment by lunaryorn** [comment]
@avdv I'm very happy that you take over. I just tried to transfer the repo, though, but failed; it looks as if there's still a repository by this name under your account—I guess it's your fork of this repo.

Would you mind to rename/remove it so that I can try the transfer again?

**Comment by avdv** [comment]
> Would you mind to rename/remove it so that I can try the transfer again?

Yes! Done. Please try again.

**Comment by lunaryorn** [comment]
See #7

**Comment by lunaryorn** [comment]
@avdv I still can't transfer; the error message now says that you "have a repository in the play-json-refined" network.  I guess you actually need to delete the fork.

I invited you as a collaborator to give you push access so that you can push all changes from your fork to this repo before deleting it.

Please ping me once you deleted it and I'll try again :)

**Comment by avdv** [comment]
> I invited you as a collaborator to give you push access so that you can push all changes from your fork to this repo before deleting it.

I have just deleted the repo, got the changes still here locally.

> Please ping me once you deleted it and I'll try again :)

ping... :)

**Pull request closed without merging**
